
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: test-service-withResilient4j
          uri: http://localhost:8091
          predicates:
            - Path=/testService/**
          filters:
            - RewritePath=/testService/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: testCircuitBreaker
                fallbackUri: forward:/fallback/testService
server:
  port: 8088
management:
  health:
    circuitbreakers:
      enabled: true